openapi: "3.0.2"
info:
  title: My UFMS APIs
  version: "1.0.0"
  description: API construida na arquitetura de micro serviços para supir serviços da rede social interna da UFMS.
  contact:
    name: Murilo Arelhano
    email: murilo.arelhano@hotmail.com
    
  

servers:
  - url: http://localhost:3333/v1


paths:
  /user/delete/all:
    post:
      description: Delete all user information
      responses:
        '200':
          description: OK
  /user/update/profile:
    post:
      description: Update user profile info
      responses:
        '200':
          description: OK

  /auth/signup:
    post:
      responses:
        "200":
          description: OK

  /auth/signin:
    post:
      responses:
        "200":
          description: ok

components:
  securitySchemes:
    name:
      type: http
      scheme: bearer
      bearerFormat: JWT