version: "3.8"

services:
  user-db:
    image: postgres
    volumes:
      - pgdata-user:/var/lib/postgresql/user
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - microservices-network
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: users

  post-db:
    image: postgres
    volumes:
      - pgdata-post:/var/lib/postgresql/post
    ports:
      - 5433:5432
    expose:
      - 5433
    networks:
      - microservices-network
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: posts

  user-api:
    image: muriloarelhano/myufms:user-api
    build:
      context: ../../user-service
      dockerfile: Dockerfile
    ports:
      - 3333:4444
    depends_on:
      - user-db
    networks:
      - microservices-network

    environment:
      NODE_ENV: production
      PROD_SERVER_PORT: 4444

  post-api:
    image: muriloarelhano/myufms:post-api
    build:
      context: ../../post-service
      dockerfile: Dockerfile
    ports:
      - 3334:4445
    depends_on:
      - post-db
      - user-api
    networks:
      - microservices-network

    environment:
      NODE_ENV: production
      PROD_SERVER_PORT: 4445
      USER_SERVICE_HOST: user-api
      USER_SERVICE_PORT: 4444

networks:
  microservices-network:
    driver: "overlay"

volumes:
  pgdata-user:
  pgdata-post:
