version: "3.8"

services:
  user-service-db:
    image: postgres
    volumes:
      - pgdata-user:/var/lib/postgresql/user
    ports:
      - 5432:5432
    expose:
      - "5432"
    networks:
      - backend
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: users

  post-service-db:
    image: postgres
    volumes:
      - pgdata-post:/var/lib/postgresql/post
    ports:
      - 5433:5432
    expose:
      - "5433"
    networks:
      - backend
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: posts

  user-service-api:
    image: myufms/user-service
    build:
      context: ../../user-service
      dockerfile: Dockerfile
    ports:
      - 3334:3334
    depends_on:
      - user-service-db
    networks:
      - backend
    environment:
      NODE_ENV: production
      PROD_SERVER_PORT: 3334

  post-service-api:
    image: myufms/post-service
    build:
      context: ../../post-service
      dockerfile: Dockerfile
    ports:
      - 4445:4445
    depends_on:
      - post-service-db
      - user-service-api
    networks:
      - backend
    environment:
      NODE_ENV: production
      PROD_SERVER_PORT: 4445
      USER_SERVICE_HOST: user-service-db
      USER_SERVICE_PORT: 3334

networks:
  backend:
    driver: "overlay"

volumes:
  pgdata-user:
  pgdata-post:
