openapi: "3.0.0"
info:
  title: My UFMS APIs
  version: "1.0.0"
  description: API construida na arquitetura de micro serviços para suprir serviços da rede social interna da UFMS.
  contact:
    name: Murilo Arelhano
    email: murilo.arelhano@hotmail.com

servers:
  - url: http://localhost:3334/v1

tags:
  - name: "Auth"
    description: "Autenticação para aplicações"
  - name: "User"
    description: "Controle de usuários"
  - name: "Profile"
    description: "Controler do profile dos usuários"
  - name: "Gender"
    description: "Controle de generos"

paths:

  /auth/signin:
    post:
      tags:
        - Auth
      summary: Signin on auth service
      description: Return a JWT token to authorization user
      requestBody:
        required: true
        description: Send user and password
        content:
          application/json:
            schema:
              $ref: "#components/schemas/signin"
      responses:
        "200":
          description: ok
  /auth/signup:
    post:
      tags:
        - Auth
      summary: Create a new user
      description: Create a new user and before creating a profile for the user
      requestBody:
        required: true
        description: User information to register
        content:
          application/json:
            schema:
              $ref: "#components/schemas/signup"

      responses:
        "200":
          description: OK

  /gender:
    get:
      tags:
        - Gender
      description: Returns all genders
      responses:
        "200":
          description: OK
    post:
      tags:
        - "Gender"
      description: Create a new gender for users
      responses:
        "200":
          description: OK
    delete:
      description: Delete a gender by id or name
      responses: 
        "200":
          description: OK

  /gender/all:
    get:
      tags:
        - Gender
      description: Returns a gender by id or name
      responses:
        "200":
          description: OK


  /user:
    delete:
      tags:
        - User
      description: Delete all user information
      responses:
        "200":
          description: OK

    get:
      description: Get all user information
      responses:
        "200":
          description: OK

components:
  schemas:
    signup:
      type: object
      properties:
        email:
          type: string
          required:
            - "email"
        password:
          type: string
        phone:
          type: string
        birthdate:
          type: string
        genderName || genderId:
          type: string
    signin:
      type: object
      properties:
        email:
          type: string
        password:
          type: string

  securitySchemes:
    cookieAuth:
      in: cookie
      type: apiKey
      name: usrJwtToken

security:
  - cookieAuth: []
